### ISSUE TITLE
[UI] Wireframes Todo

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/Music-Quiz#8]
**Опис:**

- [x]  Заголовки повинні співпадати із текстом табів

- [x]  Змінити вибраний таб (с. 5, Повинен бути вибраний створити вікторину)

- [x]  Описати текстове поле "Жанр" на сторінці "Створення тесту"

**Comment by RomanYanchuk** [comment]
[Wireframes.pdf](https://github.com/Programming-Engineering-Pmi-33/Music-Quiz/files/5287113/Wireframes.pdf)
